{
	"name": "cd",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"concurrency": {
		"group": "${{ github.ref }}",
		"cancel-in-progress": true
	},
	"permissions": {
		"contents": "read",
		"pages": "write",
		"id-token": "write"
	},
	"jobs": {
		"create-release": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
          "uses": "googleapis/release-please-action@v4",
          "with": {
            "token": "${{ secrets.PAT }}",
            "release-type": "python"
          }
        }
			]
		}
	}
}
