{
	"name": "ci",
	"on": {
		"pull_request": {
			"branches": ["main"]
		}
	},
	"concurrency": {
		"group": "${{ github.ref }}",
		"cancel-in-progress": true
	},
	"jobs": {
		"build-and-test": {
			"runs-on": "ubuntu-latest",
			"strategy": {
				"matrix": {
					"script": ["build", "test"]
				}
			},
			"steps": [
				{ "uses": "actions/checkout@v4", "with": { "ref": "dev" } },
				{ "uses": "actions/setup-node@v4" },
				{ "uses": "actions/setup-python@v5" },

				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npm run ${{ matrix.script }}" }
			],
			"timeout-minutes": 15
		},
		"merge-pull-request": {
			"runs-on": "ubuntu-latest",
			"needs": ["build-and-test"],
			"steps": [
				{
					"run": "gh pr merge --auto --merge ${{ steps.cpr.outputs.pull-request-number }}",
					"working-directory": "main",
					"env": {
						"GH_TOKEN": "${{ secrets.PAT }}"
					}
				}
			],
			"timeout-minutes": 15
		}
	}
}
