{
	"name": "ci",
	"on": {
		"pull_request": {
			"branches": ["main"]
		}
	},
	"concurrency": {
		"group": "${{ github.ref }}",
		"cancel-in-progress": true
	},
	"jobs": {
		"build-and-test": {
			"runs-on": "ubuntu-latest",
			"strategy": {
				"matrix": {
					"script": ["build", "test"]
				}
			},
			"steps": [
				{ "uses": "actions/checkout@v4", "with": { "ref": "main" } },
				{ "uses": "actions/setup-python@v5" },
				{
					"run": "gh pr merge --auto --merge ${{ github.event.number }}",
					"env": {
						"GH_TOKEN": "${{ secrets.PAT }}"
					}
				}
			],
			"timeout-minutes": 15
		}
	}
}
